### ISSUE TITLE
Domain Flag only Processes Permutations

### ISSUE THREAD

**Issue by zeknox** [bbb31/slurp#2] opened 2017-12-04 16:55 UTC
Trying to run the tool for the first time.  Love the idea for S3 enumeration, great work.

I've cloned the repo, ran the ./build.sh and all compiles great.  Currently running on a MAC OS X system and running the binary below will only yield the following output.

Looks like it starts the process of permutations, and that is it.  I get the prompt back in the terminal and it appears that nothing is running in the background.  Please advise if this is user error or expected behavior.

<pre>$ ./slurp-macos-amd64 domain --domain google.com
INFO[0000] Starting to process permutations....    
$</pre>

**Comment by bbb31** [comment] 2017-12-04 17:54
Can you confirm that you are on latest commits? I noticed this bug about 2 hours ago and did some fixes; it should be OK now. But, need to confirm.

**Comment by zeknox** [comment] 2017-12-04 17:56
Thanks for the update, Slurp was compiled using commit: 8df0c35ce2d12220cb7aeb0a5539c0f77a3a092f

**Comment by bbb31** [comment] 2017-12-04 18:02
I just published a new release that should have this fix. Tested about 20x and cant reproduce it. But if you are able to, let me know ;)

**Comment by bbb31** [comment] 2017-12-04 18:05
If you really want to be sure:

`for i in $(seq 1 25); do ./slurp domain --domain google.com; done`

:+1:  for me, closing

**Closed by bbb31** 2017-12-04 18:05 UTC

**Comment by zeknox** [comment] 2017-12-04 18:07
That worked boss!  Just updated via git, re-compiled and im back in the game, cheers!
